logging:
    level:
        org.hibernate: WARN
        org.springframework: WARN
    file: server.log

spring:
    datasource:
            url: jdbc:mysql://127.0.0.1:3306/zeyi-hyr?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
            username: root
            password: 123456
            hikari:
                minimumIdle: 5
                maximumPoolSize: 15
                data-source-properties:
                    cachePrepStmts: true
                    prepStmtCacheSize: 256
                    prepStmtCacheSqlLimit: 2048
                    useServerPrepStmts: true
    jpa:
        show-sql: false
        hibernate:
            # Hibernate DDL  auto: create, create-drop, update, validate
            ddl-auto: validate
        properties:
            hibernate.dialect: org.hibernate.dialect.MySQL5Dialect